### ISSUE TITLE
GraphQL support

### ISSUE THREAD

**Issue by nloum** [Superflows-AI/superflows#191]
I'm developing an app that exposes a GraphQL API. What would it take to be able to upload my graphql schema when setting up superflows for my app? I'd rather not have to create a REST API just to integrate.

**Comment by Henry-Pulver** [comment]
Hi @nloum, thanks so much for reaching out! :smile:

Sadly, we don't support GraphQL yet, although it's on our roadmap

I would be really interested in understanding your usecase better - quite possible it will lead to this being bumped heavily up the priority list, since only 1 other company we've spoken to have explicitly requested GraphQL. If you're happy to, get in touch on [Slack](https://join.slack.com/t/superflowsusers/shared_invite/zt-1z8ls9rp3-bSohOrMKOsX8zJOUcDy07g) or via [email](mailto:henry@superflows.ai) - whichever is easier for you :smile:

**Comment by Henry-Pulver** [comment]
@nloum, thought I'd bump here - would be great to better understand your usecase & can totally see this being highly prioritised if you do :smile:
